@baseUrl = http://localhost:3000/api/v1

### 1. Test Endpoint: Get Token (Murni Buka Browser)
GET {{baseUrl}}/token
Accept: application/json

---

### 2. Test Endpoint: Direct Search NIK Anda (Cepat & Cache)
POST {{baseUrl}}/search
Content-Type: application/json
Accept: application/json

{
  "nik": "3172041506010002"
}

---

### 3. Test Endpoint: Direct Search NIK Dummy (Cepat & Cache)
# Mengetes respons raw HTML jika NIK tidak terdaftar
POST {{baseUrl}}/search
Content-Type: application/json
Accept: application/json

{
  "nik": "123456789012"
}

---

### 4. Test Endpoint: Health Check
GET http://localhost:3000/health
Accept: application/json
